import { Project } from "@/types";


export const projects: Project[] = [
    {
        id:1,
        title: 'E-commerce Platform',
        description: 'A full-stack e-commerce platform built with Next.js, TypeScript, and Tailwind CSS.',
        technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Stripe'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/e-commerce-website.png',
      },
      {
        id:2,
        title: 'Task Management App',
        description: 'A collaborative task management application with real-time updates.',
        technologies: ['React', 'Node.js', 'MongoDB', 'Socket.io'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/task-manager.webp',
      },
      {
        id:3,
        title: 'Portfolio Website',
        description: 'My personal portfolio website showcasing my projects and skills.',
        technologies: ['Next.js', 'Tailwind CSS', 'Framer Motion'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/portfolio-website.jpg',
      },
      {
        id:4,
        title: 'Blog Platform',
        description: 'A blogging platform with user authentication and markdown support.',
        technologies: ['Gatsby', 'GraphQL', 'Contentful'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/blog-website.jpeg',
      },
      {
        id:5,
        title: 'Weather App',
        description: 'A weather application that provides real-time weather updates.',
        technologies: ['React', 'OpenWeatherMap API'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/weather-app.png',
      },
      {
        id:6,
        title: 'Chat Application',
        description: 'A real-time chat application using WebSocket technology.',
        technologies: ['React', 'Node.js', 'Socket.io'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/chat-app.png',
      },
      {
        id:7,
        title: 'Recipe Finder',
        description: 'A recipe search application using the Edamam API.',
        technologies: ['React', 'Edamam API'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/recipe-finder.png',
      },
      {
        id:8,
        title: 'Expense Tracker',
        description: 'A personal finance tracker to manage expenses and income.',
        technologies: ['React', 'Firebase'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/expense-tracker.webp',
      }
  ];