import { Project } from "@/types";


export const projects: Project[] = [
    {
        id:1,
        title: 'Employee Management System',
        description: 'A full-stack Employee Management System ,to add,update,view and delete details',
        technologies: ['ReactJs','NodeJs','MongoDb','MERN Stack'],
        githubLink: 'https://github.com',
        demoLink: 'https://sherry-ems.netlify.app',
        image: '/projects/ems.png',
      },
      {
        id:2,
        title: 'Task Management App',
        description: 'A collaborative task management application with real-time updates.',
        technologies: ['React', 'Node.js', 'MongoDB', 'Socket.io'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/task-manager.webp',
      },
      {
        id:3,
        title: 'Portfolio Website',
        description: 'My personal portfolio website showcasing my projects and skills.',
        technologies: ['Next.js', 'Tailwind CSS', 'Framer Motion'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/portfolio-website.jpg',
      },
      {
        id:4,
        title: 'Modern Landing Page',
        description: 'A Simple site to demonstate the frontend skills',
        technologies: ['ReactJs', 'TypeScript', 'Tailswind-Css','Motion-Animation'],
        githubLink: 'https://github.com',
        demoLink: 'https://react-landing-page-tailswind-vite.vercel.app',
        image: '/projects/modern-landing-page.png',
      },
      {
        id:5,
        title: 'MyTutor Landing Site',
        description: 'A simple site to express the advanced skills ',
        technologies: ['React', 'Tailswind-css','Motion-Animation','TypeScript'],
        githubLink: 'https://github.com',
        demoLink: 'https://my-tutor-landing-page-ochre.vercel.app',
        image: '/projects/mytutor.png',
      },
      {
        id:6,
        title: 'Chat Application',
        description: 'A real-time chat application using WebSocket technology.',
        technologies: ['React', 'Node.js', 'Socket.io'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/chat-app.png',
      },
      {
        id:7,
        title: 'Recipe Finder',
        description: 'A recipe search application using the Theme API.',
        technologies: ['Javascript', 'API'],
        githubLink: 'https://github.com',
        demoLink: 'https://sheryps.github.io/foodapp-using-api/',
        image: '/projects/recipy.png',
      },
      {
        id:8,
        title: 'Expense Tracker',
        description: 'A personal finance tracker to manage expenses and income.',
        technologies: ['React'],
        githubLink: 'https://github.com',
        demoLink: 'https://sherry-buget-calculator.netlify.app',
        image: '/projects/exp-tracker.png',
      }
  ];